version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  pre_build:
    commands:
      - echo Preparing for build...
  build:
    commands:
      - echo Build started on 'date'
      - npm run build
  post_build:
    commands:
      - echo Build completed on 'date'
      - echo Deploying to S3...
      - aws s3 sync build/ s3://www.azlanmalik.tech --delete --debug

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  discard-paths: yes

cache:
  paths:
    - 'node_modules/**/*'
