version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14  
    commands:
      - npm install   

  pre_build:
    commands:
      - npm run build 

artifacts:
  files:
    - '**/*'  # Include all files in the artifact

cache:
  paths:
    - node_modules/**/*  # Cache node_modules to speed up future builds
